version: 0.0
os: linux
files:
  - source: /
    destination: /webapp
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: ec2-user
      timeout: 3600
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 3600
      runas: ec2-user
